/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IRegistry, IRegistryInterface } from "../../src/IRegistry";

const _abi = [
  {
    inputs: [],
    name: "createFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_govToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_memberToken",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_leaders",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "_quorum",
        type: "uint8",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistryInterface {
    return new utils.Interface(_abi) as IRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegistry {
    return new Contract(address, _abi, signerOrProvider) as IRegistry;
  }
}
