/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721_Chamber,
  IERC721_ChamberInterface,
} from "../../../src/Chamber.sol/IERC721_Chamber";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721_Chamber__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721_ChamberInterface {
    return new utils.Interface(_abi) as IERC721_ChamberInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721_Chamber {
    return new Contract(address, _abi, signerOrProvider) as IERC721_Chamber;
  }
}
