/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chamberSol from "./Chamber.sol";
export type { chamberSol };
export type { IChamber } from "./IChamber";
export type { IRegistry } from "./IRegistry";
export type { LinkedList } from "./LinkedList";
export type { Registry } from "./Registry";
