/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chamberSol from "./Chamber.sol";
export type { chamberSol };
export type { LinkedList } from "./LinkedList";
